apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend-service
  name: udagram-frontend-service
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
  selector:
    service: udagram-frontend-service
